### ISSUE TITLE
Uncaught exception on KCLI.exe at 0x00007FF95B63C648 (ucrtbase.dll)

### ISSUE THREAD

**Issue by JstBora** [allogic/KDBG#1]
First of all, thank you for sharing this beautiful work. An exception is thrown when I try to compile the project.

> Uncaught exception on KCLI.exe at 0x00007FF95B63C648 (ucrtbase.dll): An invalid parameter was sent to a function that considers invalid parameters unrecoverable.

How can I solve this?

**Comment by allogic** [comment]
Hello,

exceptions aren't thrown at compile time and since u didn't bluescreen either, it is hard to tell what u tried to achieve.
There will be a new version of KDBG soon. Maybe that will resolve your problem.

Sincerely,
Michael
